service: session

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  versionFunctions: false
  releasedVersion: v1
  stackName: ${self:service}-${self:custom.stage}
  region: ap-southeast-1 # this is the region that we deploy our lambda to
  environment:
    item_table: Session-${self:custom.stage}
  iamRoleStatements:
    - Effect: "Allow" # or Deny
      Resource: "*"
      Action: # this is the action against dynamodb
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchWriteItem"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"

plugins:
  - serverless-domain-manager
custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: apis.banhji.com
    staging: staging-apis.banhji.com
    dev: dev-apis.banhji.com
  customDomain:
    basePath: ${self:service}
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: ${self:custom.stage}
    createRout53Record: true

package:
  individually: true
  patterns:
    - "!**/*"

functions:
  sessionCreate:
    handler: api/session/add.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/functions/functions.js
        - api/session/add.js
      individually: true
    events:
      - http:
          path: session/institute/{institute_id}/create
          method: post
          cors: true
  sessionGet:
    handler: api/session/get.get
    package:
      patterns:
        - config/**
        - api/session/get.js
      individually: true
    events:
      - http:
          path: session/institute/{institute_id}/get/{id}
          method: get
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  sessionGets:
    handler: api/session/get.gets
    package:
      patterns:
        - config/**
        - api/session/get.js
      individually: true
    events:
      - http:
          path: session/institute/{institute_id}/list
          method: get
          cors: true
          request:
            parameters:
              paths:
                institute_id: true